### ISSUE TITLE
Epic: Refactor cg-site

### ISSUE THREAD

**Issue by sknep** [cloud-gov/cg-site#2541]
These are the general needs for bringing cloud.gov's website up to date.

You can do this in whatever order makes sense!
As you get to the work, flesh these out into real tickets, real acceptance criteria, etc. Feel free to review w/ team
Open PRs as you go, with federalist links. OK to have some stuff 'broken' as you work it out.
Add me and @pburkholder as reviewers for this work.

```[tasklist]
### Tasks
- [ ] https://github.com/cloud-gov/site/issues/1
- [x] Jekyll => eleventy (build, webpack, .eleventyconfig.js, etc. slightly different flavors of liquid in the templates)
- [ ] Better integrate pages with cloud (UX/nav, also developer experience / editing)
- [x] Upgrade USWDS from v2 to v3 (https://designsystem.digital.gov/documentation/migration/)
- [ ] Update search.gov implementation to API, perhaps facets or index rather than standalone page, segment docs between pages and cloud (https://search.gov/indexing/metadata.html#searchgov-custom-fields )
- [ ] Content updates ( see sitemap list here: https://docs.google.com/spreadsheets/d/15JjoaESsE9jzEAcR5jXK9-k8pQJ0DM-5jDVHDzQa0E0/edit  and this summary from Q2 here: https://docs.google.com/document/d/1IGr4MreXIqjKr8UDNucXuLDBjKqz_x1fRQvwaPwN88I/edit )
- [ ] ... specifically: remove the mentions of 18F that make it sound like they are still owning cloud.gov
- [ ] ... specifically: simplify / remove redundant content -- say the thing once and link to it rather than repeat it
- [ ] ... specifically: unify content/article formats within the groups (Knowledge base, news/blogs)
- [x] ... specifically: migrate PDF content to HTML, delete the old PDFs
- [ ] ... specifically: remove (preferred) or clearly identify and norefer/nofollow any external links to non .gov sites
- [ ] ... specifically: redirect any removed URLs to the next newest content
- [ ] ... specifically: capitalize Cloud.gov everywhere
- [ ] ... specifically: alt text for images/accessibility issues
- [ ] Improved Pricing pages (w/ design support)
- [ ] Generate a feed of news posts for the dashboard team to consume (work w/ @cannandev for the specifics)
- [ ] Other improvements as you come upon
- [ ] https://github.com/cloud-gov/site/issues/23
- [ ] https://github.com/cloud-gov/site/issues/24
- [ ] https://github.com/cloud-gov/site/issues/25
- [ ] https://github.com/cloud-gov/cg-site/issues/2563
- [ ] https://github.com/cloud-gov/site/issues/32
- [ ] https://github.com/cloud-gov/site/issues/37
- [ ] https://github.com/cloud-gov/site/issues/40
- [ ] https://github.com/cloud-gov/site/issues/53
- [ ] https://github.com/cloud-gov/site/issues/54
- [ ] https://github.com/cloud-gov/site/issues/55
- [ ] https://github.com/cloud-gov/site/issues/56
- [ ] https://github.com/cloud-gov/site/issues/62
- [ ] https://github.com/cloud-gov/site/issues/61
- [ ] https://github.com/cloud-gov/site/issues/60
- [ ] https://github.com/cloud-gov/site/issues/59
- [ ] https://github.com/cloud-gov/site/issues/58
```

**Comment by semicoloncharmedlife** [comment]
Forwarded to https://github.com/cloud-gov/site/issues/1
Need to readdress these items later, but let's get things migrated 1 to 1 first.

**Comment by svenaas** [comment]
Reopening this to use in place of https://github.com/cloud-gov/cg-site/issues/2548 as the Pages Studio epic tracking this work.

**Comment by markdboyd** [comment]
Repo is being archived, closing this issue.
