### ISSUE TITLE
PI40 Platform Outreach Epic

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cg-site#2549]
As a current or potential customer, I want to know how to best to use
cloud.gov from new content and outreach events
so that I can acquire the platform or use it more successfully

```[tasklist]
### Tasks
- [ ] ~~For cloud.gov at ten, submit a proposal to SRECon by 11/4~~
- [ ] #2550
- [ ] Schedule PI40 Office Hour demos
- [ ] Publish Customer Story
- [ ] Revive monthly newsletter?
- [ ] https://github.com/cloud-gov/cg-site/issues/2554
```

**Comment by pburkholder** [comment]
Last week I spoke with I spoke w/ a former Cust Success / BD person w/ Cloud.gov. Some points:

Most appealing features to sell to USGov:

- Making ATO easier has come up the most times
  - Not always the developer experience
  - More important is time and $$ saved in ATO
  - However, not always great at handoff from 18F/COE to standalone agency sustenance
  - Contributing to ATO
    - Inheritance of Controls
    - Constraints are a bonus
 - Agencies don't know their own ATO process
   - Our guidance at Cloud.gov helps
  - Probably more support hours we can build in to help navigate
- IAAs and billing consistency
  - customers love consistent $$ and ability to adjust spend down at end of month

Getting Vendors

- There is a commercial CF (SAP) with six months where vendors can try CF
- Cloud.gov misses opptys here - we should pitch directly to Vendors
  - CX summit
  - Code for America
- How can we make it easier for agencies to get prototyping accounts, and then make those available to vendors for building POCs????

Support Hours

- Source of income and a key to success
- We have the staffing, lets not let this go to waste
- Track and nudge
