### ISSUE TITLE
Update demo repos and website pages referencing them

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cg-site#2554]
A current cloud.gov customer suggested that we make non-trivial examples of cloud.gov use readily accessible to potential (and existing) customers. Doing so would make it easier to understand power and flexibility and power of our platform.

We have created a number of demos over the years, so we should make them more discoverable, and easier to use.

```[tasklist]
### Tasks
- [ ] Rename repos to use "demo-" prefix in cloud-gov
- [ ] Update this website to reference repos, likely at https://cloud.gov/docs/deployment/frameworks/#sample-applications-to-deploy
- [ ] Ensure READMEs make sense, and they in turn refer to "frameworks" page
- [ ] Make sure each demo launches an application with a distinctive application name, e.g ."demo-walkthru"
- [ ] Publish newsletter item referencing these demos
- [ ] Create logging dashboard to track how often the distinctively named apps are launched
```

We can track success of this by measuring how often the demos are run.

Demos could include:
* cg-workshop
* demo-ab-testing
* demo-walk-through
* demo-app-event-queue
* intranet-demo
* cf-rshiny-demo, shiny-example
* Drupal?? - cf-ex-drupal
* cf-ex-wordpress
* space-egress-examples
* tech-talk-internal-routes
* tech-talk-rolling-updates

Others with the name "example", ex-, demo-, and so on should be explicity marked as NOT MAINTAINED.

**Comment by markdboyd** [comment]
Repo is being archived, closing this issue.
